# Generated by Django 4.2.3 on 2023-08-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/%Y/%m/%d/"),
        ),
    ]
