# Generated by Django 4.2.3 on 2023-08-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
